// 经核验的 YouTube 视频目录。所有字段中的 original / channel / publishedAt / lengthSeconds / viewCount
// 均来自 2026-09-12 对 YouTube 页面元数据的直接核验（见 SOURCES.md）；title 为编者撰写的中文标题。
// credentials 描述发布者身份，不代表临床审核，也不表示视频适合每一个人。
export const videoCatalog = [
  {
    id: "IQ-h2WuJhXM", regions: ["hip"],
    title: "髋屈肌紧绷：三方向髋部拉伸",
    original: "Tight Hip Flexors? Try This 3-Way Hip Stretch!",
    channel: "AskDoctorJo", channelId: "UCjdxelARHGq3-3dN_neMOAQ",
    publishedAt: "2026-08-03", lengthSeconds: 231, viewCount: 23093,
    kind: "拉伸", credentials: "Jo · PT / DPT", publisherType: "PT",
    sourceUrl: "https://www.askdoctorjo.com/", tags: ["髋屈肌","拉伸","2026 新发布"],
  },
  {
    id: "dLPbwnRXEHo", regions: ["shoulder"],
    title: "冻结肩 4 个温和练习：医生示范",
    original: "Fix Frozen Shoulder. 4 Gentle Exercises demonstrate by a physio and doctor",
    channel: "Doctor O'Donovan", channelId: "UCnSg7AKhnTGnac-3zGdv5Qg",
    publishedAt: "2026-07-19", lengthSeconds: 388, viewCount: 33826,
    kind: "活动度", credentials: "英国执业医师（Dr. James O'Donovan, MD），物理治疗师参与示范", publisherType: "MD",
    sourceUrl: "https://www.youtube.com/channel/UCnSg7AKhnTGnac-3zGdv5Qg", tags: ["肩部","冻结肩","医生"],
  },
  {
    id: "7fM5dZFYjZ8", regions: ["forearm"],
    title: "腕管综合征 6 分钟跟练",
    original: "Carpal Tunnel Exercises To Eliminate Tingling [6-Min Follow-Along]",
    channel: "Tone and Tighten", channelId: "UCJASBOyF4Fkd26SIwRhLuZw",
    publishedAt: "2026-07-09", lengthSeconds: 444, viewCount: 113938,
    kind: "神经滑动", credentials: "物理治疗师（Jared Beckstrand, DPT）", publisherType: "PT",
    sourceUrl: "https://www.youtube.com/channel/UCJASBOyF4Fkd26SIwRhLuZw", tags: ["腕管综合征","神经滑动","跟练","6 分钟"],
  },
  {
    id: "avgWyexgGFc", regions: ["thigh","hip","calf","lowerBack"],
    title: "全身拉伸跟练：紧张肌肉恢复",
    original: "Full Body Stretch For Tight Muscles, Recovery, and Mobility",
    channel: "Tone and Tighten", channelId: "UCJASBOyF4Fkd26SIwRhLuZw",
    publishedAt: "2026-07-02", lengthSeconds: 655, viewCount: 149742,
    kind: "跟练", credentials: "物理治疗师（Jared Beckstrand, DPT）", publisherType: "PT",
    sourceUrl: "https://www.youtube.com/channel/UCJASBOyF4Fkd26SIwRhLuZw", tags: ["全身","拉伸","跟练","10 分钟"],
  },
  {
    id: "LPWCic92xyU", regions: ["neck"],
    title: "颈痛三步方案：评估、活动与强化",
    original: "3 Steps That Fix 90% of Neck Pain!",
    channel: "Squat University", channelId: "UCyPYQTT20IgzVw92LDvtClw",
    publishedAt: "2026-06-28", lengthSeconds: 769, viewCount: 151299,
    kind: "康复讲解", credentials: "物理治疗师（Aaron Horschig, DPT）", publisherType: "PT",
    sourceUrl: "https://squatuniversity.com", tags: ["颈部","康复讲解","活动度"],
  },
  {
    id: "zpr6IfvYh6k", regions: ["abs"],
    title: "腹直肌分离：3 个核心练习（力量）",
    original: "Diastasis Recti Exercises: 3 Proven Ways to Strengthen Your Core",
    channel: "Rehab Science", channelId: "UCrJhTwfygi-D-slK4gbZ8fA",
    publishedAt: "2026-06-17", lengthSeconds: 597, viewCount: 17016,
    kind: "拉伸与力量", credentials: "物理治疗师（Tom Walters, DPT, OCS）", publisherType: "PT",
    sourceUrl: "https://www.rehabscience.com", tags: ["腹直肌","核心","拉伸与力量"],
  },
  {
    id: "1xOpTPHjVhI", regions: ["hip","lowerBack"],
    title: "髋紧引发腰痛：8 分钟跟练",
    original: "Tight Hips Causing Lower Back Pain? 8-Minute Fix (Follow Along)",
    channel: "Tone and Tighten", channelId: "UCJASBOyF4Fkd26SIwRhLuZw",
    publishedAt: "2026-05-07", lengthSeconds: 552, viewCount: 36712,
    kind: "跟练", credentials: "物理治疗师（Jared Beckstrand, DPT）", publisherType: "PT",
    sourceUrl: "https://www.youtube.com/channel/UCJASBOyF4Fkd26SIwRhLuZw", tags: ["髋部","腰部","跟练","8 分钟"],
  },
  {
    id: "1kd6REfdfKs", regions: ["neck"],
    title: "落枕后的颈部缓解：5 分钟方法",
    original: "Fix Neck Pain After Sleeping Wrong in 5 Minutes",
    channel: "Bob & Brad", channelId: "UCmTe0LsfEbpkDpgrxKAWbRA",
    publishedAt: "2026-04-09", lengthSeconds: 535, viewCount: 14620,
    kind: "拉伸", credentials: "物理治疗师（Bob Schrupp & Brad Heineck, PT）", publisherType: "PT",
    sourceUrl: "https://bobandbrad.com", tags: ["颈部","落枕","拉伸"],
  },
  {
    id: "cXL5fZ7-Tg8", regions: ["lowerBack","hip"],
    title: "NHS：坐骨神经痛缓解与练习",
    original: "Sciatica pain relief, exercises and treatment | NHS",
    channel: "NHS", channelId: "UCbVg41jzM8UroywvEr73Pdw",
    publishedAt: "2026-04-08", lengthSeconds: 210, viewCount: 121033,
    kind: "康复讲解", credentials: "英国国家医疗服务体系（NHS）", publisherType: "publicHealth",
    sourceUrl: "https://www.nhs.uk", tags: ["坐骨神经痛","腰部","NHS"],
  },
  {
    id: "lKMlqd0KaLE", regions: ["shoulder"],
    title: "抬臂肩痛：恢复过顶活动度",
    original: "3 Best Exercises for Shoulder Pain When Lifting Your Arm (Regain Overhead Mobility)",
    channel: "Rehab Science", channelId: "UCrJhTwfygi-D-slK4gbZ8fA",
    publishedAt: "2026-04-01", lengthSeconds: 408, viewCount: 32918,
    kind: "活动度", credentials: "物理治疗师（Tom Walters, DPT, OCS）", publisherType: "PT",
    sourceUrl: "https://www.rehabscience.com", tags: ["肩部","活动度","康复"],
  },
  {
    id: "nIBWGZ5CbB0", regions: ["calf"],
    title: "足底筋膜炎：7 个每日拉伸",
    original: "7 Daily Stretches for Plantar Fasciitis | Fix heel pain today with these Physio led exercises",
    channel: "Doctor O'Donovan", channelId: "UCnSg7AKhnTGnac-3zGdv5Qg",
    publishedAt: "2026-03-15", lengthSeconds: 554, viewCount: 34905,
    kind: "拉伸", credentials: "英国执业医师（Dr. James O'Donovan, MD），物理治疗师参与示范", publisherType: "MD",
    sourceUrl: "https://www.youtube.com/channel/UCnSg7AKhnTGnac-3zGdv5Qg", tags: ["足底筋膜","拉伸","医生"],
  },
  {
    id: "kKS5m2aVxjQ", regions: ["neck"],
    title: "颈部与斜方肌紧张：拉伸配合强化",
    original: "Neck STILL Tight? [Fix Neck And Trapezius Pain FOR GOOD!]",
    channel: "Tone and Tighten", channelId: "UCJASBOyF4Fkd26SIwRhLuZw",
    publishedAt: "2026-02-26", lengthSeconds: 545, viewCount: 53852,
    kind: "拉伸与力量", credentials: "物理治疗师（Jared Beckstrand, DPT）", publisherType: "PT",
    sourceUrl: "https://www.youtube.com/channel/UCJASBOyF4Fkd26SIwRhLuZw", tags: ["颈部","斜方肌","拉伸与力量"],
  },
  {
    id: "Ig874TZU_G8", regions: ["lowerBack"],
    title: "腰痛缓解：10 个最佳腰部拉伸",
    original: "10 Best Low Back Stretches for Pain Relief",
    channel: "Bob & Brad", channelId: "UCmTe0LsfEbpkDpgrxKAWbRA",
    publishedAt: "2026-02-26", lengthSeconds: 750, viewCount: 9877,
    kind: "拉伸", credentials: "物理治疗师（Bob Schrupp & Brad Heineck, PT）", publisherType: "PT",
    sourceUrl: "https://bobandbrad.com", tags: ["腰部","拉伸","腰痛"],
  },
  {
    id: "g_JmnYrwqiA", regions: ["hip"],
    title: "松解紧张髋屈肌：缓解腰髋痛",
    original: "Unlock Tight Hip Flexors in Minutes to Ease Back & Hip Pain",
    channel: "Bob & Brad", channelId: "UCmTe0LsfEbpkDpgrxKAWbRA",
    publishedAt: "2026-02-19", lengthSeconds: 827, viewCount: 20782,
    kind: "拉伸", credentials: "物理治疗师（Bob Schrupp & Brad Heineck, PT）", publisherType: "PT",
    sourceUrl: "https://bobandbrad.com", tags: ["髋屈肌","拉伸","髋部"],
  },
  {
    id: "cUI53tysUeA", regions: ["chest"],
    title: "肋软骨炎：胸部拉伸与活动度",
    original: "Costochondritis Rehab Exercises: Physical Therapy Stretches & Mobility for Chest Pain Relief",
    channel: "Rehab Science", channelId: "UCrJhTwfygi-D-slK4gbZ8fA",
    publishedAt: "2026-02-18", lengthSeconds: 594, viewCount: 12769,
    kind: "拉伸", credentials: "物理治疗师（Tom Walters, DPT, OCS）", publisherType: "PT",
    sourceUrl: "https://www.rehabscience.com", tags: ["胸部","拉伸","康复"],
  },
  {
    id: "7WWvkFYm7yY", regions: ["abs"],
    title: "呼吸与放松实时跟练",
    original: "Real-Time Breathing & Relaxation Routine",
    channel: "AskDoctorJo", channelId: "UCjdxelARHGq3-3dN_neMOAQ",
    publishedAt: "2026-02-16", lengthSeconds: 1069, viewCount: 8992,
    kind: "跟练", credentials: "物理治疗师（Jo Saunders, DPT）", publisherType: "PT",
    sourceUrl: "https://www.askdoctorjo.com", tags: ["膈肌呼吸","放松","跟练","18 分钟"],
  },
  {
    id: "mlh5ExWWkVo", regions: ["forearm"],
    title: "手部与手腕：实时拉伸和活动跟练",
    original: "Follow Along Hand / Wrist Stretching & Exercise Routine",
    channel: "AskDoctorJo", channelId: "UCjdxelARHGq3-3dN_neMOAQ",
    publishedAt: "2026-02-09", lengthSeconds: 1518, viewCount: 9607,
    kind: "跟练", credentials: "Jo · PT / DPT", publisherType: "PT",
    sourceUrl: "https://www.askdoctorjo.com/", tags: ["手腕","前臂","跟练"],
  },
  {
    id: "qHzJavfNAO0", regions: ["hip"],
    title: "9 个髋部拉伸：医生与物理治疗师",
    original: "9 Hip Stretches for Tight Hips | Doctor and Physio led guide",
    channel: "Doctor O'Donovan", channelId: "UCnSg7AKhnTGnac-3zGdv5Qg",
    publishedAt: "2026-02-06", lengthSeconds: 998, viewCount: 114631,
    kind: "拉伸", credentials: "英国执业医师（Dr. James O'Donovan, MD），物理治疗师参与示范", publisherType: "MD",
    sourceUrl: "https://www.youtube.com/channel/UCnSg7AKhnTGnac-3zGdv5Qg", tags: ["髋部","拉伸","医生","16 分钟"],
  },
  {
    id: "X8wSvJvT7QQ", regions: ["calf"],
    title: "踝部与足部：实时拉伸和活动跟练",
    original: "Real-Time Ankle / Foot Stretching & Exercise Routine",
    channel: "AskDoctorJo", channelId: "UCjdxelARHGq3-3dN_neMOAQ",
    publishedAt: "2026-02-02", lengthSeconds: 1608, viewCount: 9629,
    kind: "跟练", credentials: "Jo · PT / DPT", publisherType: "PT",
    sourceUrl: "https://www.askdoctorjo.com/", tags: ["踝部","足部","跟练"],
  },
  {
    id: "B5qMJshogTM", regions: ["shoulder","upperBack","neck","arm"],
    title: "肩部跟练：肩颈拉伸与上臂等长练习",
    original: "Real-Time Shoulder Stretching & Exercise Routine",
    channel: "AskDoctorJo", channelId: "UCjdxelARHGq3-3dN_neMOAQ",
    publishedAt: "2026-01-26", lengthSeconds: 1760, viewCount: 12659,
    kind: "拉伸与力量", credentials: "Jo · PT / DPT", publisherType: "PT",
    sourceUrl: "https://www.askdoctorjo.com/product/14-beginner-shoulder-stretches-exercises-worksheet/", tags: ["斜方肌","肩胛提肌","上臂等长练习"],
  },
  {
    id: "5cRbDPWavhI", regions: ["lowerBack"],
    title: "10 分钟腰部活动度跟练",
    original: "10 Min Mobility For FAST Lower Back Pain Relief! [PT GUIDED]",
    channel: "Tone and Tighten", channelId: "UCJASBOyF4Fkd26SIwRhLuZw",
    publishedAt: "2026-01-22", lengthSeconds: 632, viewCount: 441476,
    kind: "跟练", credentials: "物理治疗师（Jared Beckstrand, DPT）", publisherType: "PT",
    sourceUrl: "https://www.youtube.com/channel/UCJASBOyF4Fkd26SIwRhLuZw", tags: ["腰部","活动度","跟练","10 分钟"],
  },
  {
    id: "vtH-OJZiOAk", regions: ["hip","thigh"],
    title: "臀髋与大腿跟练：腘绳肌、股四头肌和髋屈肌",
    original: "Real-Time Hip Stretching & Exercise Routine",
    channel: "AskDoctorJo", channelId: "UCjdxelARHGq3-3dN_neMOAQ",
    publishedAt: "2026-01-19", lengthSeconds: 1617, viewCount: 11803,
    kind: "跟练", credentials: "Jo · PT / DPT", publisherType: "PT",
    sourceUrl: "https://www.askdoctorjo.com/product/13-beginner-hip-stretches-exercises-worksheet/", tags: ["腘绳肌","股四头肌","髋屈肌"],
  },
  {
    id: "vXeAzjavyyI", regions: ["arm"],
    title: "上臂疼痛的真正原因与练习",
    original: "The REAL Cause of Your Upper Arm Pain (Plus 3 Exercises to Fix It)",
    channel: "Dr. Dave Candy - Physical Therapist", channelId: "UCCOEPGVhYOsEq166gSK-jpw",
    publishedAt: "2026-01-17", lengthSeconds: 621, viewCount: 34077,
    kind: "康复讲解", credentials: "物理治疗师（Dave Candy, DPT）", publisherType: "PT",
    sourceUrl: "https://www.youtube.com/channel/UCCOEPGVhYOsEq166gSK-jpw", tags: ["上臂","康复讲解","肩袖"],
  },
  {
    id: "VSLOSu637B8", regions: ["shoulder"],
    title: "肩袖康复跟练：PT 引导",
    original: "Fix Shoulder Pain For Good! [PT-Guided Rotator Cuff Routine]",
    channel: "Tone and Tighten", channelId: "UCJASBOyF4Fkd26SIwRhLuZw",
    publishedAt: "2026-01-15", lengthSeconds: 825, viewCount: 116101,
    kind: "拉伸与力量", credentials: "物理治疗师（Jared Beckstrand, DPT）", publisherType: "PT",
    sourceUrl: "https://www.youtube.com/channel/UCJASBOyF4Fkd26SIwRhLuZw", tags: ["肩部","肩袖","拉伸与力量"],
  },
  {
    id: "KHxMOuylDTc", regions: ["neck"],
    title: "颈部：实时拉伸和活动跟练",
    original: "Follow Along Neck Stretching & Exercise Routine",
    channel: "AskDoctorJo", channelId: "UCjdxelARHGq3-3dN_neMOAQ",
    publishedAt: "2026-01-12", lengthSeconds: 1426, viewCount: 17323,
    kind: "跟练", credentials: "Jo · PT / DPT", publisherType: "PT",
    sourceUrl: "https://www.askdoctorjo.com/", tags: ["颈部","拉伸","跟练"],
  },
  {
    id: "r-Xw_jfSwnE", regions: ["thigh"],
    title: "腘绳肌紧的 5 个原因与解法",
    original: "5 Reasons Your Hamstrings Feel Tight & How to Fix",
    channel: "Bob & Brad", channelId: "UCmTe0LsfEbpkDpgrxKAWbRA",
    publishedAt: "2025-12-21", lengthSeconds: 1266, viewCount: 20532,
    kind: "康复讲解", credentials: "物理治疗师（Bob Schrupp & Brad Heineck, PT）", publisherType: "PT",
    sourceUrl: "https://bobandbrad.com", tags: ["腘绳肌","大腿","康复讲解"],
  },
  {
    id: "Pltr8Sd27ug", regions: ["neck"],
    title: "手机电脑颈痛：3 个简单练习",
    original: "3 Simple Exercises to Relieve Neck Pain From Computer and Phone Use",
    channel: "Rehab Science", channelId: "UCrJhTwfygi-D-slK4gbZ8fA",
    publishedAt: "2025-12-17", lengthSeconds: 346, viewCount: 23356,
    kind: "活动度", credentials: "物理治疗师（Tom Walters, DPT, OCS）", publisherType: "PT",
    sourceUrl: "https://www.rehabscience.com", tags: ["颈部","活动度","办公族"],
  },
  {
    id: "9V8oGt2hfCI", regions: ["hip"],
    title: "髋紧：比单纯拉伸更有效的做法",
    original: "Tight Hips? Here's What Works Better Than Stretching",
    channel: "Squat University", channelId: "UCyPYQTT20IgzVw92LDvtClw",
    publishedAt: "2025-12-14", lengthSeconds: 317, viewCount: 761129,
    kind: "活动度", credentials: "物理治疗师（Aaron Horschig, DPT）", publisherType: "PT",
    sourceUrl: "https://squatuniversity.com", tags: ["髋部","活动度","康复讲解"],
  },
  {
    id: "ktOw-6irlYs", regions: ["forearm"],
    title: "手麻刺痛：三条神经滑动练习",
    original: "Numb Hands or Tingling? 3 Nerve Glides That Fix Median, Ulnar & Radial Nerve Irritation",
    channel: "Rehab Science", channelId: "UCrJhTwfygi-D-slK4gbZ8fA",
    publishedAt: "2025-12-03", lengthSeconds: 384, viewCount: 89122,
    kind: "神经滑动", credentials: "物理治疗师（Tom Walters, DPT, OCS）", publisherType: "PT",
    sourceUrl: "https://www.rehabscience.com", tags: ["神经滑动","手麻","前臂"],
  },
  {
    id: "ZbHKKD7bjZo", regions: ["thigh"],
    title: "股四头肌腱炎：缓解练习",
    original: "Fix Quadriceps Tendinitis FAST! [Knee Pain Relief Exercises]",
    channel: "Tone and Tighten", channelId: "UCJASBOyF4Fkd26SIwRhLuZw",
    publishedAt: "2025-11-20", lengthSeconds: 872, viewCount: 102941,
    kind: "拉伸与力量", credentials: "物理治疗师（Jared Beckstrand, DPT）", publisherType: "PT",
    sourceUrl: "https://www.youtube.com/channel/UCJASBOyF4Fkd26SIwRhLuZw", tags: ["股四头肌","大腿","拉伸与力量"],
  },
  {
    id: "iuNbRNYhkOs", regions: ["lowerBack"],
    title: "腰背拉伸：3 个动作示范",
    original: "Top 3 Back Pain Relief Stretches",
    channel: "AskDoctorJo", channelId: "UCjdxelARHGq3-3dN_neMOAQ",
    publishedAt: "2025-11-10", lengthSeconds: 83, viewCount: 20908,
    kind: "拉伸", credentials: "Jo · PT / DPT", publisherType: "PT",
    sourceUrl: "https://www.askdoctorjo.com/", tags: ["腰背","拉伸"],
  },
  {
    id: "heplE6tpEwM", regions: ["hip"],
    title: "梨状肌疼痛：5 个动作",
    original: "5 Moves to End Piriformis Pain for Good",
    channel: "Bob & Brad", channelId: "UCmTe0LsfEbpkDpgrxKAWbRA",
    publishedAt: "2025-11-09", lengthSeconds: 738, viewCount: 87875,
    kind: "拉伸与力量", credentials: "物理治疗师（Bob Schrupp & Brad Heineck, PT）", publisherType: "PT",
    sourceUrl: "https://bobandbrad.com", tags: ["梨状肌","臀部","拉伸与力量"],
  },
  {
    id: "PUMLdpXFXWE", regions: ["neck"],
    title: "颈部拉伸示范",
    original: "Neck Pain Relief Stretches",
    channel: "AskDoctorJo", channelId: "UCjdxelARHGq3-3dN_neMOAQ",
    publishedAt: "2025-10-20", lengthSeconds: 104, viewCount: 15082,
    kind: "拉伸", credentials: "Jo · PT / DPT", publisherType: "PT",
    sourceUrl: "https://www.askdoctorjo.com/", tags: ["颈部","拉伸"],
  },
  {
    id: "CHDZm8wfptU", regions: ["neck"],
    title: "颈屈肌拉伸与活动练习",
    original: "Neck Flexors Stretches & Exercises",
    channel: "AskDoctorJo", channelId: "UCjdxelARHGq3-3dN_neMOAQ",
    publishedAt: "2025-10-06", lengthSeconds: 311, viewCount: 13531,
    kind: "拉伸", credentials: "Jo · PT / DPT", publisherType: "PT",
    sourceUrl: "https://www.askdoctorjo.com/", tags: ["颈屈肌","活动练习"],
  },
  {
    id: "OM5gzn9Vrhw", regions: ["chest","shoulder","arm","upperBack"],
    title: "10 分钟上肢拉伸跟练",
    original: "10 Min Upper Body Stretch [Flexibility, Relaxation, Recovery]",
    channel: "Tone and Tighten", channelId: "UCJASBOyF4Fkd26SIwRhLuZw",
    publishedAt: "2025-10-02", lengthSeconds: 655, viewCount: 98422,
    kind: "跟练", credentials: "物理治疗师（Jared Beckstrand, DPT）", publisherType: "PT",
    sourceUrl: "https://www.youtube.com/channel/UCJASBOyF4Fkd26SIwRhLuZw", tags: ["上肢","拉伸","跟练","10 分钟"],
  },
  {
    id: "6pvlSkSqVMI", regions: ["abs","lowerBack"],
    title: "预防腰痛的 8 个核心练习",
    original: "8 Best Core Exercises That PREVENT Low Back Pain",
    channel: "Bob & Brad", channelId: "UCmTe0LsfEbpkDpgrxKAWbRA",
    publishedAt: "2025-09-25", lengthSeconds: 770, viewCount: 37855,
    kind: "拉伸与力量", credentials: "物理治疗师（Bob Schrupp & Brad Heineck, PT）", publisherType: "PT",
    sourceUrl: "https://bobandbrad.com", tags: ["核心","腹部","腰痛","拉伸与力量"],
  },
  {
    id: "rG6hFwdZVhg", regions: ["arm"],
    title: "肱二头肌长头肌腱病：康复练习",
    original: "Upper Biceps Tendon Exercises (Proximal Biceps Tendinopathy)",
    channel: "Rehab Science", channelId: "UCrJhTwfygi-D-slK4gbZ8fA",
    publishedAt: "2025-09-16", lengthSeconds: 381, viewCount: 30426,
    kind: "康复讲解", credentials: "物理治疗师（Tom Walters, DPT, OCS）", publisherType: "PT",
    sourceUrl: "https://www.rehabscience.com", tags: ["肱二头肌","上臂","康复"],
  },
  {
    id: "CzA5_e6AmKQ", regions: ["arm","shoulder"],
    title: "肩前痛与肱二头肌腱炎缓解",
    original: "Fix Anterior Shoulder Pain [Biceps Tendonitis Pain Relief]",
    channel: "Tone and Tighten", channelId: "UCJASBOyF4Fkd26SIwRhLuZw",
    publishedAt: "2025-09-11", lengthSeconds: 644, viewCount: 60312,
    kind: "拉伸与力量", credentials: "物理治疗师（Jared Beckstrand, DPT）", publisherType: "PT",
    sourceUrl: "https://www.youtube.com/channel/UCJASBOyF4Fkd26SIwRhLuZw", tags: ["肱二头肌","肩前痛","拉伸与力量"],
  },
  {
    id: "qTnxdMXhXNs", regions: ["thigh"],
    title: "腹股沟痛：内收肌 4 个练习",
    original: "4 Groin Pain Exercises (Adductor Muscle Strains and Tendinopathy)",
    channel: "Rehab Science", channelId: "UCrJhTwfygi-D-slK4gbZ8fA",
    publishedAt: "2025-09-02", lengthSeconds: 507, viewCount: 67491,
    kind: "康复讲解", credentials: "物理治疗师（Tom Walters, DPT, OCS）", publisherType: "PT",
    sourceUrl: "https://www.rehabscience.com", tags: ["内收肌","大腿","康复"],
  },
  {
    id: "jJ3dJe6ff2Q", regions: ["hip"],
    title: "髋部旋转活动度：两个练习步骤",
    original: "Improve Your Hip Rotation Mobility (2 Simple Steps)",
    channel: "E3 Rehab", channelId: "UCkb9jgRxR2D5bc1fSDofwtA",
    publishedAt: "2025-08-08", lengthSeconds: 90, viewCount: 56663,
    kind: "活动度", credentials: "物理治疗博士团队", publisherType: "PT",
    sourceUrl: "https://www.youtube.com/watch?v=jJ3dJe6ff2Q", tags: ["髋内旋","髋外旋","活动度"],
  },
  {
    id: "aMJER9zwIY8", regions: ["lowerBack"],
    title: "7 分钟腰痛拉伸跟练",
    original: "FAST Lower Back Pain Relief! [7-Min Follow-Along Stretches]",
    channel: "Tone and Tighten", channelId: "UCJASBOyF4Fkd26SIwRhLuZw",
    publishedAt: "2025-08-07", lengthSeconds: 450, viewCount: 171659,
    kind: "跟练", credentials: "物理治疗师（Jared Beckstrand, DPT）", publisherType: "PT",
    sourceUrl: "https://www.youtube.com/channel/UCJASBOyF4Fkd26SIwRhLuZw", tags: ["腰部","拉伸","跟练","7 分钟"],
  },
  {
    id: "l65F8a2z10I", regions: ["upperBack"],
    title: "上胸椎活动度：3 个练习",
    original: "3 Upper Thoracic Mobility Exercises",
    channel: "Rehab Science", channelId: "UCrJhTwfygi-D-slK4gbZ8fA",
    publishedAt: "2025-06-18", lengthSeconds: 431, viewCount: 20746,
    kind: "活动度", credentials: "物理治疗师（Tom Walters, DPT, OCS）", publisherType: "PT",
    sourceUrl: "https://www.rehabscience.com", tags: ["胸椎","活动度","上背部"],
  },
  {
    id: "KS65hyDJOlw", regions: ["abs"],
    title: "膈肌呼吸示范（达特茅斯健康）",
    original: "How to use Diaphragmatic Breathing for GI Conditions",
    channel: "Dartmouth Health", channelId: "UCN2GyOp5NJ99pe7OY6Agvtg",
    publishedAt: "2025-06-17", lengthSeconds: 194, viewCount: 12545,
    kind: "康复讲解", credentials: "达特茅斯健康（美国学术医疗系统）", publisherType: "hospital",
    sourceUrl: "https://www.dartmouth-health.org", tags: ["膈肌呼吸","腹部","医院"],
  },
  {
    id: "2t5pK3_pl-M", regions: ["lowerBack"],
    title: "腰椎间盘疼痛：每日康复练习",
    original: "Fix Your Lumbar Disc Pain With These Daily Prehab Exercises (Includes Assessment)",
    channel: "[P]rehab", channelId: "UCZOrpZTHi21RZpnxXdlJbgQ",
    publishedAt: "2025-06-16", lengthSeconds: 1350, viewCount: 7185,
    kind: "康复讲解", credentials: "物理治疗博士团队（The Prehab Guys, DPT）", publisherType: "PT",
    sourceUrl: "https://theprehabguys.com", tags: ["腰椎间盘","腰部","康复讲解"],
  },
  {
    id: "xCiQcY7pOmE", regions: ["neck"],
    title: "克利夫兰诊所：居家缓解颈痛要点",
    original: "Tips To Relieve Neck Pain at Home | Ask Cleveland Clinic's Expert",
    channel: "Cleveland Clinic", channelId: "UCxyiSz4m161Z6frOsFxJpgw",
    publishedAt: "2025-05-26", lengthSeconds: 193, viewCount: 3686,
    kind: "康复讲解", credentials: "克利夫兰诊所（美国学术医疗中心）", publisherType: "hospital",
    sourceUrl: "https://my.clevelandclinic.org", tags: ["颈部","康复讲解","医院"],
  },
  {
    id: "RntFYZLpUbo", regions: ["neck","shoulder","upperBack"],
    title: "HSS 坐姿拉伸：颈、肩、背",
    original: "Seated Stretch Break (Neck, Shoulder, Back) | HSS",
    channel: "Hospital for Special Surgery", channelId: "UCtiGeFDbY7iVDODlLKQ5onw",
    publishedAt: "2025-05-22", lengthSeconds: 140, viewCount: 31301,
    kind: "跟练", credentials: "骨科专科医院（美国特种外科医院 HSS）", publisherType: "hospital",
    sourceUrl: "https://www.hss.edu", tags: ["颈部","肩部","坐姿","跟练"],
  },
  {
    id: "STg1aNdTIwk", regions: ["forearm","neck"],
    title: "HSS 坐姿拉伸：手、腕与颈",
    original: "Seated Stretch Break (Hand, Wrist, Neck) | HSS",
    channel: "Hospital for Special Surgery", channelId: "UCtiGeFDbY7iVDODlLKQ5onw",
    publishedAt: "2025-05-22", lengthSeconds: 149, viewCount: 124359,
    kind: "跟练", credentials: "骨科专科医院（美国特种外科医院 HSS）", publisherType: "hospital",
    sourceUrl: "https://www.hss.edu", tags: ["手腕","颈部","坐姿","跟练"],
  },
  {
    id: "EawrBR8p81o", regions: ["shoulder","chest","upperBack"],
    title: "HSS 坐姿拉伸：上半身",
    original: "Seated Stretch Break (Upper Body) | HSS",
    channel: "Hospital for Special Surgery", channelId: "UCtiGeFDbY7iVDODlLKQ5onw",
    publishedAt: "2025-05-22", lengthSeconds: 149, viewCount: 71192,
    kind: "跟练", credentials: "骨科专科医院（美国特种外科医院 HSS）", publisherType: "hospital",
    sourceUrl: "https://www.hss.edu", tags: ["上半身","坐姿","跟练","医院"],
  },
  {
    id: "9BDqQmK3a2w", regions: ["lowerBack","hip","thigh"],
    title: "HSS 坐姿拉伸：下半身",
    original: "Seated Stretch Break (Lower Body) | HSS",
    channel: "Hospital for Special Surgery", channelId: "UCtiGeFDbY7iVDODlLKQ5onw",
    publishedAt: "2025-05-22", lengthSeconds: 211, viewCount: 72735,
    kind: "跟练", credentials: "骨科专科医院（美国特种外科医院 HSS）", publisherType: "hospital",
    sourceUrl: "https://www.hss.edu", tags: ["下半身","坐姿","跟练","医院"],
  },
  {
    id: "x71Y5ijW4DU", regions: ["lowerBack"],
    title: "腰背康复：活动练习与循证讲解",
    original: "Lower Back Pain Rehab (Exercises | Education | Myths | Prevention)",
    channel: "E3 Rehab", channelId: "UCkb9jgRxR2D5bc1fSDofwtA",
    publishedAt: "2025-05-18", lengthSeconds: 1245, viewCount: 73148,
    kind: "康复讲解", credentials: "物理治疗博士团队 · 附研究引用", publisherType: "PT",
    sourceUrl: "https://e3rehab.com/low-back-pain-rehab/", tags: ["腰背","活动练习","教育讲解"],
  },
  {
    id: "60UuEf8IbUo", regions: ["forearm"],
    title: "网球肘修复：3 个简单步骤",
    original: "How to Fix Tennis Elbow! (3 Easy Steps)",
    channel: "Bob & Brad", channelId: "UCmTe0LsfEbpkDpgrxKAWbRA",
    publishedAt: "2025-05-15", lengthSeconds: 934, viewCount: 49909,
    kind: "康复讲解", credentials: "物理治疗师（Bob Schrupp & Brad Heineck, PT）", publisherType: "PT",
    sourceUrl: "https://bobandbrad.com", tags: ["网球肘","前臂","康复讲解"],
  },
  {
    id: "BQOJa9o-j8g", regions: ["calf"],
    title: "足底筋膜炎：正确的处理思路",
    original: "How To Fix Plantar Fasciitis Pain [You’re Doing It Wrong]",
    channel: "Tone and Tighten", channelId: "UCJASBOyF4Fkd26SIwRhLuZw",
    publishedAt: "2025-05-08", lengthSeconds: 654, viewCount: 564088,
    kind: "康复讲解", credentials: "物理治疗师（Jared Beckstrand, DPT）", publisherType: "PT",
    sourceUrl: "https://www.youtube.com/channel/UCJASBOyF4Fkd26SIwRhLuZw", tags: ["足底筋膜","足部","康复讲解"],
  },
  {
    id: "yPagCi2WZJE", regions: ["forearm"],
    title: "高尔夫球肘：拉伸与强化",
    original: "STOP Elbow Pain! Best Exercises For Golfer’s Elbow [Medial Epicondylitis]",
    channel: "Tone and Tighten", channelId: "UCJASBOyF4Fkd26SIwRhLuZw",
    publishedAt: "2025-04-24", lengthSeconds: 748, viewCount: 189699,
    kind: "拉伸与力量", credentials: "物理治疗师（Jared Beckstrand, DPT）", publisherType: "PT",
    sourceUrl: "https://www.youtube.com/channel/UCJASBOyF4Fkd26SIwRhLuZw", tags: ["高尔夫球肘","前臂","拉伸与力量"],
  },
  {
    id: "T64es5lGZr8", regions: ["neck"],
    title: "5 分钟颈部拉伸跟练",
    original: "FAST Neck Pain Relief! [5-Minute Follow-Along Stretches]",
    channel: "Tone and Tighten", channelId: "UCJASBOyF4Fkd26SIwRhLuZw",
    publishedAt: "2025-04-17", lengthSeconds: 333, viewCount: 648693,
    kind: "跟练", credentials: "物理治疗师（Jared Beckstrand, DPT）", publisherType: "PT",
    sourceUrl: "https://www.youtube.com/channel/UCJASBOyF4Fkd26SIwRhLuZw", tags: ["颈部","拉伸","跟练","5 分钟"],
  },
  {
    id: "P5G6sn9Uf28", regions: ["forearm"],
    title: "肘痛原因与应对：完整讲解",
    original: "Why Your Elbow Hurts (And What To Do About It!)",
    channel: "E3 Rehab", channelId: "UCkb9jgRxR2D5bc1fSDofwtA",
    publishedAt: "2025-03-02", lengthSeconds: 1183, viewCount: 454779,
    kind: "康复讲解", credentials: "物理治疗博士团队（E3 Rehab, DPT）", publisherType: "PT",
    sourceUrl: "https://e3rehab.com", tags: ["肘部","康复讲解","20 分钟"],
  },
  {
    id: "Scq9hboii8I", regions: ["upperBack"],
    title: "上背痛：提升胸椎活动度",
    original: "Fix Your Upper Back Pain! [Increase Your Thoracic Mobility]",
    channel: "Tone and Tighten", channelId: "UCJASBOyF4Fkd26SIwRhLuZw",
    publishedAt: "2025-02-06", lengthSeconds: 474, viewCount: 24006,
    kind: "活动度", credentials: "物理治疗师（Jared Beckstrand, DPT）", publisherType: "PT",
    sourceUrl: "https://www.youtube.com/channel/UCJASBOyF4Fkd26SIwRhLuZw", tags: ["胸椎","活动度","上背部"],
  },
  {
    id: "Lz5zAPgxGD4", regions: ["hip"],
    title: "髋部疼痛：理解原因与练习选择",
    original: "Why Your Hip Hurts (And What To Do About It!)",
    channel: "E3 Rehab", channelId: "UCkb9jgRxR2D5bc1fSDofwtA",
    publishedAt: "2025-01-26", lengthSeconds: 1860, viewCount: 267934,
    kind: "康复讲解", credentials: "物理治疗博士团队 · 附研究引用", publisherType: "PT",
    sourceUrl: "https://e3rehab.com/why-your-hip-hurts/", tags: ["髋部","教育讲解","练习选择"],
  },
  {
    id: "nMqlUEK1iis", regions: ["neck","upperBack"],
    title: "肩胛区疼痛：上斜方肌与肩胛提肌",
    original: "Shoulder Blade Pain Exercises (Upper Trapezius, Levator Scapulae, Cervical Referral)",
    channel: "Rehab Science", channelId: "UCrJhTwfygi-D-slK4gbZ8fA",
    publishedAt: "2025-01-24", lengthSeconds: 517, viewCount: 45830,
    kind: "拉伸与力量", credentials: "物理治疗师（Tom Walters, DPT, OCS）", publisherType: "PT",
    sourceUrl: "https://www.rehabscience.com", tags: ["颈部","肩胛提肌","上背部"],
  },
  {
    id: "8AeojB3Nphg", regions: ["lowerBack","hip"],
    title: "解锁腰部与髋部：每日拉伸",
    original: "Unlock Your Lower Back And Hips! [Daily Stretching Routine]",
    channel: "Tone and Tighten", channelId: "UCJASBOyF4Fkd26SIwRhLuZw",
    publishedAt: "2025-01-16", lengthSeconds: 447, viewCount: 340013,
    kind: "跟练", credentials: "物理治疗师（Jared Beckstrand, DPT）", publisherType: "PT",
    sourceUrl: "https://www.youtube.com/channel/UCJASBOyF4Fkd26SIwRhLuZw", tags: ["腰部","髋部","拉伸","跟练"],
  },
  {
    id: "g_QdfmVB8Yc", regions: ["thigh"],
    title: "腘绳肌紧：拉伸之外的力量方案",
    original: "Fix Tight Hamstrings FOR GOOD! (Stop Stretching)",
    channel: "Tone and Tighten", channelId: "UCJASBOyF4Fkd26SIwRhLuZw",
    publishedAt: "2024-12-26", lengthSeconds: 592, viewCount: 469969,
    kind: "拉伸与力量", credentials: "物理治疗师（Jared Beckstrand, DPT）", publisherType: "PT",
    sourceUrl: "https://www.youtube.com/channel/UCJASBOyF4Fkd26SIwRhLuZw", tags: ["腘绳肌","大腿","拉伸与力量"],
  },
  {
    id: "c8aPTN_f3co", regions: ["calf"],
    title: "跟腱炎：最佳自我处理",
    original: "Achilles Tendonitis: Absolute Best Self-Treatment",
    channel: "Bob & Brad", channelId: "UCmTe0LsfEbpkDpgrxKAWbRA",
    publishedAt: "2024-12-19", lengthSeconds: 398, viewCount: 21986,
    kind: "康复讲解", credentials: "物理治疗师（Bob Schrupp & Brad Heineck, PT）", publisherType: "PT",
    sourceUrl: "https://bobandbrad.com", tags: ["跟腱","小腿","康复讲解"],
  },
  {
    id: "MpXKUvaqfp0", regions: ["shoulder"],
    title: "肩痛原因与应对：完整讲解",
    original: "Why Your Shoulder Hurts (And What To Do About It!)",
    channel: "E3 Rehab", channelId: "UCkb9jgRxR2D5bc1fSDofwtA",
    publishedAt: "2024-11-24", lengthSeconds: 1425, viewCount: 344346,
    kind: "康复讲解", credentials: "物理治疗博士团队（E3 Rehab, DPT）", publisherType: "PT",
    sourceUrl: "https://e3rehab.com", tags: ["肩部","康复讲解","24 分钟"],
  },
  {
    id: "Nw4dAqLzm6A", regions: ["shoulder"],
    title: "解锁紧绷或冻结肩",
    original: "How to Unlock Your Tight or Frozen Shoulder!",
    channel: "Bob & Brad", channelId: "UCmTe0LsfEbpkDpgrxKAWbRA",
    publishedAt: "2024-11-19", lengthSeconds: 823, viewCount: 30289,
    kind: "活动度", credentials: "物理治疗师（Bob Schrupp & Brad Heineck, PT）", publisherType: "PT",
    sourceUrl: "https://bobandbrad.com", tags: ["肩部","冻结肩","活动度"],
  },
  {
    id: "Ms7hJlBN3gA", regions: ["calf"],
    title: "比目鱼肌拉伸：NHS inform 示范",
    original: "Calf Muscle Stretch (soleus)",
    channel: "NHS inform", channelId: "UC_f1D-UUq9QnvsMsVRVxVSA",
    publishedAt: "2024-11-15", lengthSeconds: 57, viewCount: 10312,
    kind: "拉伸", credentials: "苏格兰 NHS 官方健康信息服务", publisherType: "publicHealth",
    sourceUrl: "https://www.nhsinform.scot/illnesses-and-conditions/muscle-bone-and-joints/leg-and-foot-problems-and-conditions/exercises-for-foot-conditions", tags: ["比目鱼肌","屈膝小腿拉伸","单个动作"],
  },
  {
    id: "Lg_V6XuUkHQ", regions: ["chest","upperBack"],
    title: "圆肩驼背：3 步姿势矫正方案",
    original: "Fix Your Bad Posture PERMANENTLY! [3 Simple Steps]",
    channel: "Tone and Tighten", channelId: "UCJASBOyF4Fkd26SIwRhLuZw",
    publishedAt: "2024-10-17", lengthSeconds: 616, viewCount: 101901,
    kind: "拉伸与力量", credentials: "物理治疗师（Jared Beckstrand, DPT）", publisherType: "PT",
    sourceUrl: "https://www.youtube.com/channel/UCJASBOyF4Fkd26SIwRhLuZw", tags: ["姿势","胸部","拉伸与力量"],
  },
  {
    id: "xtHH-_SQZbM", regions: ["hip"],
    title: "梨状肌综合征：诊断与练习",
    original: "Piriformis Syndrome (Diagnosis | Myths | Stretching & Strengthening Exercises)",
    channel: "E3 Rehab", channelId: "UCkb9jgRxR2D5bc1fSDofwtA",
    publishedAt: "2024-09-29", lengthSeconds: 558, viewCount: 257574,
    kind: "康复讲解", credentials: "物理治疗博士团队（E3 Rehab, DPT）", publisherType: "PT",
    sourceUrl: "https://e3rehab.com", tags: ["梨状肌","臀部","康复讲解"],
  },
  {
    id: "rDwhVzNTsNY", regions: ["forearm"],
    title: "5 分钟前臂疼痛缓解练习",
    original: "Forearm Pain Relief Exercises in 5 min",
    channel: "Jeffrey Peng MD", channelId: "UCL5eiGK1f0A-DecaBqq5emg",
    publishedAt: "2024-09-28", lengthSeconds: 412, viewCount: 104601,
    kind: "拉伸", credentials: "Jeffrey Peng · 运动医学医师", publisherType: "MD",
    sourceUrl: "https://www.jeffreypengmd.com/", tags: ["前臂","手腕","疼痛缓解"],
  },
  {
    id: "7c-tAnd0jss", regions: ["thigh"],
    title: "腘绳肌拉伸示范",
    original: "Hamstring Stretch",
    channel: "Michigan Orthopedic Center", channelId: "UCJhfdpxZ9XZXwm0soKjB44A",
    publishedAt: "2024-09-26", lengthSeconds: 33, viewCount: 8595,
    kind: "拉伸", credentials: "骨科医疗机构", publisherType: "hospital",
    sourceUrl: "https://www.youtube.com/watch?v=7c-tAnd0jss", tags: ["腘绳肌","单个动作"],
  },
  {
    id: "kubv4YY6LYo", regions: ["calf"],
    title: "小腿疼痛：拉伸与强化练习",
    original: "How To Fix Calf Pain! [Stretches and Exercises For Calf Pain Relief]",
    channel: "Tone and Tighten", channelId: "UCJASBOyF4Fkd26SIwRhLuZw",
    publishedAt: "2024-09-19", lengthSeconds: 597, viewCount: 71294,
    kind: "拉伸与力量", credentials: "物理治疗师（Jared Beckstrand, DPT）", publisherType: "PT",
    sourceUrl: "https://www.youtube.com/channel/UCJASBOyF4Fkd26SIwRhLuZw", tags: ["小腿","拉伸与力量","腓肠肌"],
  },
  {
    id: "15GPO-s0UVw", regions: ["hip","thigh","calf"],
    title: "HSS 6 分钟下肢活动度练习",
    original: "6-Minute Mobility Exercises for Fall Prevention (HSS)",
    channel: "Hospital for Special Surgery", channelId: "UCtiGeFDbY7iVDODlLKQ5onw",
    publishedAt: "2024-09-12", lengthSeconds: 413, viewCount: 338578,
    kind: "活动度", credentials: "骨科专科医院（美国特种外科医院 HSS）", publisherType: "hospital",
    sourceUrl: "https://www.hss.edu", tags: ["下肢","活动度","跟练","医院"],
  },
  {
    id: "ELKH26jRZB0", regions: ["shoulder"],
    title: "手背后够不着？肩内旋活动度",
    original: "Reach Behind Your Back (Shoulder Mobility Exercises)",
    channel: "Rehab Science", channelId: "UCrJhTwfygi-D-slK4gbZ8fA",
    publishedAt: "2024-09-03", lengthSeconds: 242, viewCount: 100933,
    kind: "活动度", credentials: "物理治疗师（Tom Walters, DPT, OCS）", publisherType: "PT",
    sourceUrl: "https://www.rehabscience.com", tags: ["肩部","活动度","内旋"],
  },
  {
    id: "7-EXcqSMR9E", regions: ["forearm"],
    title: "6 分钟手腕拉伸跟练",
    original: "Fix Your Wrist Pain FAST! [6-Minute Stretching Routine]",
    channel: "Tone and Tighten", channelId: "UCJASBOyF4Fkd26SIwRhLuZw",
    publishedAt: "2024-08-29", lengthSeconds: 378, viewCount: 147952,
    kind: "跟练", credentials: "物理治疗师（Jared Beckstrand, DPT）", publisherType: "PT",
    sourceUrl: "https://www.youtube.com/channel/UCJASBOyF4Fkd26SIwRhLuZw", tags: ["手腕","拉伸","跟练","6 分钟"],
  },
  {
    id: "La7BAQKlXAk", regions: ["arm"],
    title: "肱二头肌腱炎与拉伤：康复练习讲解",
    original: "Heal Bicep Tendonitis/Strain Fast, Research Based",
    channel: "Bob & Brad", channelId: "UCmTe0LsfEbpkDpgrxKAWbRA",
    publishedAt: "2024-08-01", lengthSeconds: 494, viewCount: 79454,
    kind: "康复讲解", credentials: "物理治疗师团队", publisherType: "PT",
    sourceUrl: "https://www.youtube.com/@BobandBrad", tags: ["肱二头肌","腱炎康复"],
  },
  {
    id: "OWERjHZbfmY", regions: ["lowerBack"],
    title: "根据腰背感受选择合适的拉伸",
    original: "Best Stretches For YOUR Lower Back Pain [SO IMPORTANT!]",
    channel: "Tone and Tighten", channelId: "UCJASBOyF4Fkd26SIwRhLuZw",
    publishedAt: "2024-07-18", lengthSeconds: 741, viewCount: 1908654,
    kind: "拉伸", credentials: "Jared Beckstrand · PT / DPT", publisherType: "PT",
    sourceUrl: "https://linktr.ee/jaredbeckstranddpt", tags: ["腰背","拉伸","动作选择"],
  },
  {
    id: "Gz2ZIccRwZc", regions: ["upperBack","lowerBack"],
    title: "背痛与姿势：10 个最佳拉伸",
    original: "Absolute Best 10 Stretches For Back Pain & Perfect Posture!",
    channel: "Bob & Brad", channelId: "UCmTe0LsfEbpkDpgrxKAWbRA",
    publishedAt: "2024-07-13", lengthSeconds: 1052, viewCount: 103040,
    kind: "拉伸", credentials: "物理治疗师（Bob Schrupp & Brad Heineck, PT）", publisherType: "PT",
    sourceUrl: "https://bobandbrad.com", tags: ["背部","姿势","拉伸"],
  },
  {
    id: "fPaF3oro6hE", regions: ["hip","thigh"],
    title: "髋部活动度：旋转、屈伸与大腿内侧",
    original: "How To Improve Your Hip Range of Motion (Stretches & Mobility Exercises)",
    channel: "E3 Rehab", channelId: "UCkb9jgRxR2D5bc1fSDofwtA",
    publishedAt: "2024-06-30", lengthSeconds: 1721, viewCount: 978119,
    kind: "活动度", credentials: "Tony Comella · DPT · 附研究引用", publisherType: "PT",
    sourceUrl: "https://e3rehab.com/how-to-improve-your-hip-range-of-motion/", tags: ["髋部","内收肌","活动度"],
  },
  {
    id: "GMKt9cDPVO8", regions: ["upperBack","lowerBack"],
    title: "解锁脊柱：完整拉伸跟练",
    original: "Unlock Your Spine! Complete Stretching Routine [Follow Along]",
    channel: "Tone and Tighten", channelId: "UCJASBOyF4Fkd26SIwRhLuZw",
    publishedAt: "2024-06-06", lengthSeconds: 643, viewCount: 119600,
    kind: "跟练", credentials: "物理治疗师（Jared Beckstrand, DPT）", publisherType: "PT",
    sourceUrl: "https://www.youtube.com/channel/UCJASBOyF4Fkd26SIwRhLuZw", tags: ["脊柱","拉伸","跟练","10 分钟"],
  },
  {
    id: "FaUSbDC6WvU", regions: ["chest"],
    title: "胸部紧绷：居家改善方案",
    original: "Pec Tightness Fixed at Home | Physical Therapist",
    channel: "Rehab and Revive", channelId: "UCBaK1umRVZIaCi9o4BlQQTA",
    publishedAt: "2024-05-22", lengthSeconds: 359, viewCount: 1455,
    kind: "拉伸", credentials: "物理治疗团队", publisherType: "PT",
    sourceUrl: "https://www.rehabandrevive.com/", tags: ["胸部紧绷","活动度"],
  },
  {
    id: "JsnbWwFP7PQ", regions: ["hip"],
    title: "髋旋转活动度：评估与改善",
    original: "Maximize Your Hip Mobility: Assess & Improve Your Hip Rotation",
    channel: "[P]rehab", channelId: "UCZOrpZTHi21RZpnxXdlJbgQ",
    publishedAt: "2024-05-21", lengthSeconds: 687, viewCount: 11348,
    kind: "活动度", credentials: "物理治疗博士团队（The Prehab Guys, DPT）", publisherType: "PT",
    sourceUrl: "https://theprehabguys.com", tags: ["髋部","90/90","活动度"],
  },
  {
    id: "AMqT-3l0I6k", regions: ["shoulder"],
    title: "肩部活动与力量：5 个练习",
    original: "5 Exercises For Shoulder Pain Relief (No More Impingement!)",
    channel: "Tone and Tighten", channelId: "UCJASBOyF4Fkd26SIwRhLuZw",
    publishedAt: "2024-05-16", lengthSeconds: 581, viewCount: 1327114,
    kind: "拉伸与力量", credentials: "Jared Beckstrand · PT / DPT", publisherType: "PT",
    sourceUrl: "https://linktr.ee/jaredbeckstranddpt", tags: ["活动度","力量练习"],
  },
  {
    id: "63oscRDvoYw", regions: ["hip"],
    title: "改良梨状肌拉伸：快速简单",
    original: "Modified Piriformis Stretch - Quick & Easy!",
    channel: "AskDoctorJo", channelId: "UCjdxelARHGq3-3dN_neMOAQ",
    publishedAt: "2024-05-13", lengthSeconds: 123, viewCount: 24711,
    kind: "拉伸", credentials: "物理治疗师（Jo Saunders, DPT）", publisherType: "PT",
    sourceUrl: "https://www.askdoctorjo.com", tags: ["梨状肌","拉伸","2 分钟"],
  },
  {
    id: "p3U3Ait9p_Y", regions: ["hip"],
    title: "坐姿 90 秒拉伸全部髋部肌群",
    original: "Stretch EVERY Hip Muscle Daily In 90 Seconds (Seated)",
    channel: "Bob & Brad", channelId: "UCmTe0LsfEbpkDpgrxKAWbRA",
    publishedAt: "2024-05-09", lengthSeconds: 640, viewCount: 455315,
    kind: "拉伸", credentials: "物理治疗师（Bob Schrupp & Brad Heineck, PT）", publisherType: "PT",
    sourceUrl: "https://bobandbrad.com", tags: ["髋部","坐姿","拉伸"],
  },
  {
    id: "7xY-JrvtnC0", regions: ["forearm"],
    title: "手腕活动度跟练：6 个疼痛缓解动作",
    original: "Wrist Mobility Follow Along Routine: 6 Simple Wrist Exercises for Pain Relief",
    channel: "Virtual Hand Care", channelId: "UCtq7dohkm8vTLXqWcsoJlgw",
    publishedAt: "2024-04-05", lengthSeconds: 650, viewCount: 101707,
    kind: "跟练", credentials: "手部康复教育（Virtual Hand Care）", publisherType: "clinic",
    sourceUrl: "https://virtualhandcare.com/", tags: ["手腕","前臂","活动度"],
  },
  {
    id: "nvJ-1suJCTU", regions: ["forearm"],
    title: "手腕关节活动度：6 个练习",
    original: "6 Exercises to Improve Wrist Joint Mobility and Range of Motion",
    channel: "Rehab Science", channelId: "UCrJhTwfygi-D-slK4gbZ8fA",
    publishedAt: "2024-03-27", lengthSeconds: 447, viewCount: 47713,
    kind: "活动度", credentials: "物理治疗师（Tom Walters, DPT, OCS）", publisherType: "PT",
    sourceUrl: "https://www.rehabscience.com", tags: ["手腕","活动度","前臂"],
  },
  {
    id: "RoiWkNKDEBU", regions: ["chest","upperBack"],
    title: "胸紧圆肩的真正原因与对策",
    original: "Tight Chest, Rounded Shoulders? Here's What's Actually Causing It",
    channel: "Squat University", channelId: "UCyPYQTT20IgzVw92LDvtClw",
    publishedAt: "2024-03-26", lengthSeconds: 360, viewCount: 560515,
    kind: "康复讲解", credentials: "物理治疗师（Aaron Horschig, DPT）", publisherType: "PT",
    sourceUrl: "https://squatuniversity.com", tags: ["胸部","圆肩","康复讲解"],
  },
  {
    id: "AO8-tyuiPaE", regions: ["calf"],
    title: "踝关节活动度：四个方向练习",
    original: "How to Improve Ankle Joint Mobility (4 Directions of Movement)",
    channel: "Rehab Science", channelId: "UCrJhTwfygi-D-slK4gbZ8fA",
    publishedAt: "2024-03-13", lengthSeconds: 409, viewCount: 31980,
    kind: "活动度", credentials: "物理治疗师（Tom Walters, DPT, OCS）", publisherType: "PT",
    sourceUrl: "https://www.rehabscience.com", tags: ["踝关节","活动度","小腿"],
  },
  {
    id: "_f6-GRhgOEM", regions: ["thigh"],
    title: "腘绳肌疼痛：快速简单缓解",
    original: "Suffering from Hamstring Pain? Try This for Quick & Easy Relief!",
    channel: "AskDoctorJo", channelId: "UCjdxelARHGq3-3dN_neMOAQ",
    publishedAt: "2024-03-04", lengthSeconds: 517, viewCount: 20168,
    kind: "拉伸", credentials: "物理治疗师（Jo Saunders, DPT）", publisherType: "PT",
    sourceUrl: "https://www.askdoctorjo.com", tags: ["腘绳肌","大腿","拉伸"],
  },
  {
    id: "rmtZl-KQQwY", regions: ["shoulder"],
    title: "肩袖拉伸：5 种动作示范",
    original: "Top 5 Rotator Cuff Stretches for Shoulder Pain Relief by Physical Therapist",
    channel: "Next Level Physical Therapy", channelId: "UCuq-4OlVmjshpt0p8MKpRLQ",
    publishedAt: "2024-03-01", lengthSeconds: 301, viewCount: 560,
    kind: "拉伸", credentials: "物理治疗机构 · PT 示范", publisherType: "PT",
    sourceUrl: "https://www.youtube.com/watch?v=rmtZl-KQQwY", tags: ["肩袖","拉伸"],
  },
  {
    id: "h7UWxp9hWpg", regions: ["lowerBack","hip"],
    title: "骶髂关节疼痛：讲解与练习",
    original: "Sacroiliac (SI) Joint Pain (Education | Myths | Stretching & Strengthening Exercises)",
    channel: "E3 Rehab", channelId: "UCkb9jgRxR2D5bc1fSDofwtA",
    publishedAt: "2024-02-25", lengthSeconds: 552, viewCount: 2270960,
    kind: "康复讲解", credentials: "物理治疗博士团队（E3 Rehab, DPT）", publisherType: "PT",
    sourceUrl: "https://e3rehab.com", tags: ["骶髂关节","腰部","康复讲解"],
  },
  {
    id: "Bv2iBmyKJMQ", regions: ["shoulder"],
    title: "解锁肩部：10 个拉伸缓解紧张",
    original: "Unlock Your Shoulders! Top 10 Stretches to Relieve Tightness & Pain",
    channel: "Tone and Tighten", channelId: "UCJASBOyF4Fkd26SIwRhLuZw",
    publishedAt: "2024-02-22", lengthSeconds: 709, viewCount: 130497,
    kind: "拉伸", credentials: "物理治疗师（Jared Beckstrand, DPT）", publisherType: "PT",
    sourceUrl: "https://www.youtube.com/channel/UCJASBOyF4Fkd26SIwRhLuZw", tags: ["肩部","拉伸","10 分钟"],
  },
  {
    id: "VuhB8_j4xsg", regions: ["abs"],
    title: "改善核心与骨盆健康的 3 个舒展动作",
    original: "3 Stretches for Better Core & Pelvic Health",
    channel: "Buffalo Rehab Group", channelId: "UCgRjDU_S1_V3sPKX8VYVYfg",
    publishedAt: "2024-02-19", lengthSeconds: 132, viewCount: 1454,
    kind: "拉伸", credentials: "骨盆健康物理治疗团队", publisherType: "PT",
    sourceUrl: "https://buffalorehab.com/", tags: ["核心","腹部","骨盆健康"],
  },
  {
    id: "65Jc9j5jepw", regions: ["calf"],
    title: "足底筋膜炎：快速缓解拉伸",
    original: "Got Plantar Fasciitis? Try THIS to Relieve Pain Fast!",
    channel: "AskDoctorJo", channelId: "UCjdxelARHGq3-3dN_neMOAQ",
    publishedAt: "2024-02-19", lengthSeconds: 448, viewCount: 27110,
    kind: "拉伸", credentials: "物理治疗师（Jo Saunders, DPT）", publisherType: "PT",
    sourceUrl: "https://www.askdoctorjo.com", tags: ["足底筋膜","足部","拉伸"],
  },
  {
    id: "bOXI-wxepmI", regions: ["forearm"],
    title: "手腕疼痛跟练：拉伸与活动",
    original: "Fix Your Wrist Pain! Follow-Along Routine For Wrist Pain Relief",
    channel: "Tone and Tighten", channelId: "UCJASBOyF4Fkd26SIwRhLuZw",
    publishedAt: "2024-01-25", lengthSeconds: 701, viewCount: 1601135,
    kind: "跟练", credentials: "Jared Beckstrand · PT / DPT", publisherType: "PT",
    sourceUrl: "https://tone-and-tighten.com/", tags: ["手腕","前臂","跟练"],
  },
  {
    id: "tN60ns8ParI", regions: ["abs"],
    title: "膈肌与腹部舒展",
    original: "How To Stretch Your Diaphragm And Abdomen | Pursuit Physical Therapy",
    channel: "Pursuit Physical Therapy", channelId: "UCIvL27r2NHTVKwbrlwAKLbA",
    publishedAt: "2024-01-10", lengthSeconds: 45, viewCount: 1110,
    kind: "拉伸", credentials: "物理治疗机构", publisherType: "PT",
    sourceUrl: "https://pursuitpt.com/pursuit-pt-blog/", tags: ["腹部","膈肌","呼吸"],
  },
  {
    id: "A2KxUaOdmWY", regions: ["arm","shoulder"],
    title: "肱二头肌腱病与肩前痛：康复",
    original: "Biceps Tendinopathy / Tendinitis | Anterior Shoulder Pain Rehab (Education & Exercises)",
    channel: "E3 Rehab", channelId: "UCkb9jgRxR2D5bc1fSDofwtA",
    publishedAt: "2024-01-07", lengthSeconds: 594, viewCount: 2455601,
    kind: "康复讲解", credentials: "物理治疗博士团队（E3 Rehab, DPT）", publisherType: "PT",
    sourceUrl: "https://e3rehab.com", tags: ["肱二头肌","肩前痛","康复讲解"],
  },
  {
    id: "fTRv8dEgK3I", regions: ["neck","shoulder","upperBack"],
    title: "10 分钟颈部、肩部与上背温和拉伸",
    original: "10 Minute Gentle Stretches: Neck, Shoulder, and Upper Back Pain Relief",
    channel: "Dr. Kristie Ennis", channelId: "UCCq4wJn0zh05i5VI1jmDN5g",
    publishedAt: "2024-01-05", lengthSeconds: 641, viewCount: 681824,
    kind: "拉伸", credentials: "Kristie Ennis · DPT / CSCS", publisherType: "PT",
    sourceUrl: "https://www.pt-nh.com/about", tags: ["温和拉伸","跟练","10 分钟"],
  },
  {
    id: "0HAu2W7GpIs", regions: ["calf"],
    title: "紧绷小腿的活动与拉伸",
    original: "The Secret to Relieving Tight Calf Muscles with a physical therapist",
    channel: "Alyssa Kuhn, Arthritis Adventure", channelId: "UCrA-zi9rqRQsPGinrwVhISQ",
    publishedAt: "2024-01-04", lengthSeconds: 336, viewCount: 166214,
    kind: "拉伸", credentials: "Alyssa Kuhn · DPT", publisherType: "PT",
    sourceUrl: "https://www.youtube.com/watch?v=0HAu2W7GpIs", tags: ["小腿","活动练习"],
  },
  {
    id: "5zdmvqWfkb8", regions: ["abs"],
    title: "膈肌呼吸：简单呼吸练习",
    original: "Breathe Better with These Easy Exercises!",
    channel: "AskDoctorJo", channelId: "UCjdxelARHGq3-3dN_neMOAQ",
    publishedAt: "2023-12-11", lengthSeconds: 376, viewCount: 28452,
    kind: "康复讲解", credentials: "物理治疗师（Jo Saunders, DPT）", publisherType: "PT",
    sourceUrl: "https://www.askdoctorjo.com", tags: ["膈肌呼吸","腹部","呼吸"],
  },
  {
    id: "Y-7r3eKLlgM", regions: ["arm"],
    title: "肱二头肌远端肌腱病：4 个练习",
    original: "Bounce Back from Biceps Pain - 4 Essential Exercises for Distal Biceps Tendinopathy Relief",
    channel: "[P]rehab", channelId: "UCZOrpZTHi21RZpnxXdlJbgQ",
    publishedAt: "2023-12-05", lengthSeconds: 526, viewCount: 104453,
    kind: "康复讲解", credentials: "物理治疗博士团队（The Prehab Guys, DPT）", publisherType: "PT",
    sourceUrl: "https://theprehabguys.com", tags: ["肱二头肌","上臂","康复"],
  },
  {
    id: "xHv-G-mOzTc", regions: ["upperBack"],
    title: "上背痛缓解跟练例程",
    original: "How To Fix Upper Back Pain - Follow-Along Exercise Routine!",
    channel: "Tone and Tighten", channelId: "UCJASBOyF4Fkd26SIwRhLuZw",
    publishedAt: "2023-11-22", lengthSeconds: 559, viewCount: 154490,
    kind: "跟练", credentials: "物理治疗师（Jared Beckstrand, DPT）", publisherType: "PT",
    sourceUrl: "https://www.youtube.com/channel/UCJASBOyF4Fkd26SIwRhLuZw", tags: ["上背部","跟练","拉伸与力量"],
  },
  {
    id: "voxwcEraw6g", regions: ["shoulder"],
    title: "冻结肩：3 个康复活动度练习",
    original: "3 Frozen Shoulder Rehab Exercises",
    channel: "Rehab Science", channelId: "UCrJhTwfygi-D-slK4gbZ8fA",
    publishedAt: "2023-11-15", lengthSeconds: 434, viewCount: 83028,
    kind: "活动度", credentials: "物理治疗师（Tom Walters, DPT, OCS）", publisherType: "PT",
    sourceUrl: "https://www.rehabscience.com", tags: ["肩部","冻结肩","活动度"],
  },
  {
    id: "4GW6QdSaQ6U", regions: ["calf"],
    title: "提升踝关节活动度：拉伸与练习",
    original: "How To Improve Your Ankle Mobility (Stretches & Exercises)",
    channel: "E3 Rehab", channelId: "UCkb9jgRxR2D5bc1fSDofwtA",
    publishedAt: "2023-11-12", lengthSeconds: 904, viewCount: 882664,
    kind: "活动度", credentials: "物理治疗博士团队（E3 Rehab, DPT）", publisherType: "PT",
    sourceUrl: "https://e3rehab.com", tags: ["踝关节","活动度","小腿"],
  },
  {
    id: "mSD_YfYfy7c", regions: ["lowerBack"],
    title: "腰方肌腰痛：拉伸与强化",
    original: "Quadratus Lumborum (QL) | Low Back Pain Rehab & Exercises (Stretching | Strengthening | Education)",
    channel: "E3 Rehab", channelId: "UCkb9jgRxR2D5bc1fSDofwtA",
    publishedAt: "2023-11-05", lengthSeconds: 739, viewCount: 209226,
    kind: "康复讲解", credentials: "物理治疗博士团队（E3 Rehab, DPT）", publisherType: "PT",
    sourceUrl: "https://e3rehab.com", tags: ["腰方肌","腰部","康复讲解"],
  },
  {
    id: "VMM2czODEUs", regions: ["upperBack"],
    title: "中背部（胸椎）活动度 4 练习",
    original: "4 Mid-Back Mobility Exercises",
    channel: "Rehab Science", channelId: "UCrJhTwfygi-D-slK4gbZ8fA",
    publishedAt: "2023-10-11", lengthSeconds: 404, viewCount: 29825,
    kind: "活动度", credentials: "物理治疗师（Tom Walters, DPT, OCS）", publisherType: "PT",
    sourceUrl: "https://www.rehabscience.com", tags: ["胸椎","活动度","上背部"],
  },
  {
    id: "DlcG5r2SYb8", regions: ["thigh"],
    title: "股四头肌拉伤：康复练习",
    original: "Quad Strain? Try These Effective Exercises to Bounce Back Stronger!",
    channel: "[P]rehab", channelId: "UCZOrpZTHi21RZpnxXdlJbgQ",
    publishedAt: "2023-10-10", lengthSeconds: 1031, viewCount: 75564,
    kind: "康复讲解", credentials: "物理治疗博士团队（The Prehab Guys, DPT）", publisherType: "PT",
    sourceUrl: "https://theprehabguys.com", tags: ["股四头肌","大腿","康复"],
  },
  {
    id: "nyyY81RzNCQ", regions: ["forearm"],
    title: "手腕疼痛康复：力量、拉伸与活动度",
    original: "Wrist Pain Rehab (Strengthening & Stretching Exercises | Mobility | Education)",
    channel: "E3 Rehab", channelId: "UCkb9jgRxR2D5bc1fSDofwtA",
    publishedAt: "2023-10-08", lengthSeconds: 1715, viewCount: 204855,
    kind: "拉伸与力量", credentials: "物理治疗团队", publisherType: "PT",
    sourceUrl: "https://e3rehab.com/", tags: ["手腕","前臂","循证康复"],
  },
  {
    id: "qiz4yNsPtKQ", regions: ["chest"],
    title: "胸肌紧张疼痛：3 个缓解练习",
    original: "Top 3 Chest Pain Relief Exercises That Actually Work!",
    channel: "AskDoctorJo", channelId: "UCjdxelARHGq3-3dN_neMOAQ",
    publishedAt: "2023-09-04", lengthSeconds: 248, viewCount: 321631,
    kind: "拉伸", credentials: "物理治疗师（Jo Saunders, DPT）", publisherType: "PT",
    sourceUrl: "https://www.askdoctorjo.com", tags: ["胸部","胸肌","拉伸"],
  },
  {
    id: "YBfikh0i21w", regions: ["chest"],
    title: "圆肩矫正：6 个简单拉伸",
    original: "Fix Your Rounded Shoulders! 6 Simple Stretches To Correct Posture",
    channel: "Tone and Tighten", channelId: "UCJASBOyF4Fkd26SIwRhLuZw",
    publishedAt: "2023-03-16", lengthSeconds: 485, viewCount: 203757,
    kind: "拉伸", credentials: "物理治疗师（Jared Beckstrand, DPT）", publisherType: "PT",
    sourceUrl: "https://www.youtube.com/channel/UCJASBOyF4Fkd26SIwRhLuZw", tags: ["胸部","圆肩","拉伸"],
  },
  {
    id: "Vf3zBwDqxA8", regions: ["arm"],
    title: "肱三头肌腱病：4 个康复练习",
    original: "4 Exercises for Triceps Pain (Tendinopathy/Tendinitis Rehab)",
    channel: "Rehab Science", channelId: "UCrJhTwfygi-D-slK4gbZ8fA",
    publishedAt: "2022-10-20", lengthSeconds: 449, viewCount: 201542,
    kind: "康复讲解", credentials: "物理治疗师（Tom Walters, DPT, OCS）", publisherType: "PT",
    sourceUrl: "https://www.rehabscience.com", tags: ["肱三头肌","上臂","康复"],
  },
  {
    id: "IGRVdPNVJq8", regions: ["arm"],
    title: "5 个肩部舒展动作（含肱二头肌与肱三头肌）",
    original: "Get Sore Shoulder Relief With These 5 Gentle Stretches!",
    channel: "AskDoctorJo", channelId: "UCjdxelARHGq3-3dN_neMOAQ",
    publishedAt: "2022-01-10", lengthSeconds: 431, viewCount: 92978,
    kind: "拉伸", credentials: "Jo · PT / DPT", publisherType: "PT",
    sourceUrl: "https://www.askdoctorjo.com/video/5-sore-shoulder-stretches/", tags: ["肱二头肌","肱三头肌","肩部"],
  },
  {
    id: "WpXpM_h3f5M", regions: ["chest"],
    title: "胸大肌拉伸：NHS 物理治疗示范",
    original: "Physiotherapy: Pec stretches",
    channel: "East Cheshire NHS Trust", channelId: "UCLrD_SGpBbpnYkQvnFZ9vSA",
    publishedAt: "2017-03-22", lengthSeconds: 39, viewCount: 4314,
    kind: "拉伸", credentials: "NHS 公立医院", publisherType: "publicHealth",
    sourceUrl: "https://www.eastcheshire.nhs.uk/", tags: ["胸大肌","前肩"],
  },
];
